# Use single-quotes so string will be literal (backslashes treated as is)
# (Especially important in Windows)

[names]
dir = 'C:\Cache\SL-Carto'
db = 'RegionsDB2.pkl'
lock = 'RegionsDB2.lock'
log = 'RegionsDB2.log.yaml'
progress = 'RegionsDB2Progress.yaml'

[maps]
dir = 'C:\Cache\SL-Carto\Maps2'
lock = 'Maps.lock'
log = 'Maps.log.yaml'
progress = 'MapsProgress.yaml'

[mosaic]
domc_cache = 'CachedDominantColors.pkl'

[areas]
dir = 'C:\Cache\SL-Carto\AreaMaps'

[grids]
dir_composite = 'C:\Cache\SL-Carto\AreaMaps\Grids'
dir_gridonly = 'C:\Cache\SL-Carto\AreaMaps\Grids'
font_name = 'C:\Windows\Fonts\comic.ttf'
font_size = 16
